version: '2'
services:
    server:
      container_name: discord_server
      build:
        context: .
        dockerfile: ./Dockerfile
      ports:
        - 8060:8080
      volumes:
        - ./app
      restart: always